### ISSUE TITLE
Runtime assertion fail when trying to access flex_vector contents via iterator

### ISSUE THREAD

**Issue by DeifLou** [arximboldi/immer#48] opened 2018-05-31 22:18 UTC
I don't really understand what is going on here, if it's something wrong with immer or if it's my low skills.
The problem in the following code is trying to access the iterator thru some functions:
```cpp
#include <immer/flex_vector.hpp>
#include <immer/box.hpp>
#include <iostream>

struct A
{
    
    immer::flex_vector<immer::box<int>> v{1, 2, 3};

    auto vector() const
    {
        return v;
    }

    auto begin() const
    {
        return vector().begin();
    }

    auto end() const
    {
        return vector().end();
    }
};

int main()
{
    A a;

    for (auto i = a.begin(); i != a.end(); ++i)
        std::cout << (**i) << std::endl;
        
    // for (auto i = a.vector().begin(); i != a.vector().end(); ++i)
    //     std::cout << (**i) << std::endl;

    return 0;
}
```
If you try the commented code instead of the other, it works. As I said, I'm kind of lost...
The assertion message is:
```
Assertion failed!

Program: D:\projects\build\test\immer_test\debug\immer_test.exe
File: D:/projects/install/debug/include/immer/detail/rbts/node.hpp, Line 183

Expression: kind() == kind_t::inner

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
Environment info:
**Compiler**: GCC 7.3.0, under MSYS2/MinGW64
**Platform**: Windows 10, 64 bits

**Comment by DeifLou** [comment] 2018-05-31 22:27
Well, I used a flex_vector of boxes of ints in the previous example, but it also fails with:
```cpp
immer::flex_vector<int> v{1, 2, 3};
```

**Comment by arximboldi** [comment] 2018-06-01 15:38
In this case, the problem is in your code. The problem is that `vector()` returns a new object by value. The iterator `vector().begin()` thus returns an iterator into the temporary object that it returns. You can fix the problem by making `vector()` return `decltype(auto)` instead, or if you prefer, just explicitly `const immer::flex_vector<immer::box<int>>&`.

An alternative would be to make Immer iterators keep the data they point to alive. While these semantics would be different than on traditional iterators, it would be possible due to the immutability of the underlying data and the structural sharing that exists anyways. If I make sure this would have zero runtime costs, I might do that. Anyways in this example the solution described above is better. I'm gonna just close this issue. Cheers!

**Closed** 2018-06-01 15:47 UTC

**Comment by DeifLou** [comment] 2018-06-01 16:05
Ohhh, I see. I thought immer implemented the approach you explain in the second paragraph. Most of the issues I have using the library I can solve just by looking at its code, but there are always corners that leave me guessing...
Thanks.
